
pipelines:
  default:
    - step:
        image: elixir:1.9.0-alpine
        script:
          - apk add git
          - apk add --update nodejs npm
          - npm install newman
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - newman --version
          - mix test --color


definitions:
  services:
    redis:
      image: redis:4.0
