openapi: 3.1.0
info:
    title: LowEndInsight API Definition
    description: |
       LowEndInsight is a simple "bus-factor" risk analysis library for
       Open Source Software which is managed within a Git repository.
    version: 0.7.0
paths: {} # Flush out