# Copyright (C) 2020 by the Georgia Tech Research Institute (GTRI)
# This software may be modified and distributed under the terms of
# the BSD 3-Clause license. See the LICENSE file for details.

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: lei-get
spec:
  selector:
    matchLabels:
      app: lei-get
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: lei-get
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-master
        - name: REDIS_PORT
          value: "6379"
        name: lei-get
        image: kitplummer/lowendinsight_get:latest
        ports:
        - containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: lei-get
  labels:
    run: lei-get
spec:
  type: LoadBalancer
  ports:
  - port: 4444
    protocol: TCP
  selector:
    run: lei-get
