apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: lei-get
spec:
  selector:
    matchLabels:
      app: lei-get
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: lei-get
    spec:
      containers:
      - name: lei-get
        image: kitplummer/lowendinsight-get:0.1.0
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: lei-get
  labels:
    run: lei-get
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    protocol: TCP
  selector:
    run: lei-get
