# Copyright (C) 2020 by the Georgia Tech Research Institute (GTRI)
# This software may be modified and distributed under the terms of
# the BSD 3-Clause license. See the LICENSE file for details.

apiVersion: v1
kind: Service
metadata:
  name: lei-get
  labels:
    run: lei-get
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    protocol: TCP
  selector:
    run: lei-get
