---
version: '3'
services:
  redis-master:
    image: "redis:alpine"
  lei-get:
    image: "kitplummer/lowendinsight_get:latest"
    ports:
      - "4444:4444"
    environment:
      - REDIS_URL=redis://redis-master:6379/3
