name: default_elixir_ci

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apk add git nodejs npm make
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        newman --version
    - name: Run Tests
      run: mix test --color
    - name: Package Container
      run: |
        mix distillery.init \
        make build