name: default_elixir_ci

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    # container:
    #   image: elixir:1.9.4-alpine

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'
          number of databases: 1
      - name: Install Dependencies
        run: |
          npm install -g newman
          newman --version
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix coveralls.html
      - name: Archive code coverage report
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cover/*.html
      - name: Build Container
        run: make build
      - name: Publish to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make publish
      - name: docker-compose run LEI-get
        run: docker-compose up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Postman tests
        run: newman run test/docker-compose.postman_collection.json
