name: default_elixir_ci

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!main'     # excludes main - no pushes allowed
      - '!develop'  # excludes develop - no pushes allowed

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: elixir:1.14.1-alpine

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
      - uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'
          number of databases: 20
      - name: Install Dependencies
        run: |
          npm install -g newman
          newman --version
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: MIX_ENV=test mix coveralls.github
      - name: Build Container
        run: make build
      - name: docker-compose run LEI-get
        run: docker-compose up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Postman tests
        run: newman run test/docker-compose.postman_collection.json
      - name: Publish to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make publish-snapshot
