name: default_elixir_ci

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    # container:
    #   image: elixir:1.9.4-alpine

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - name: Install Dependencies
        run: |
          npm install -g newman
          newman --version
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix distillery.init
      - name: Run Tests
        run: mix test --color
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Build Container
        run: make build